### ISSUE TITLE
Maximum matrix size?

### ISSUE THREAD

**Issue by zumpchke** [PetteriAimonen/libfixmatrix#2]
Is the maximum matrix size 255 x 255?

**Comment by PetteriAimonen** [comment]
Yes, though the algorithms are designed for much smaller matrices. Once you get to larger than about 50x50, fixmatrix is probably not a very good choice for efficiency.

**Comment by zumpchke** [comment]
I see. Any reason why? Are you referring to the use of special instruction sets?

**Comment by PetteriAimonen** [comment]
Efficient matrix algorithms is a pretty wide topic, use of SIMD is certainly one part of it. For details you can compare implementations in e.g. BLAS vs. fixmatrix.

**Comment by zumpchke** [comment]
Thanks. Is there something like BLAS but for fixed point? I am interested in arbitrary sized matrices, but also performance gains from ditching floating point.
